
pull_request_rules:
  - name: enqueue on label
    conditions: []
    actions:
      queue:
queue_rules:
  - name: dev
    queue_conditions:
      - base=dev
      - label=merge-queue
    merge_conditions:
      - base=dev
      - label=merge-queue
    batch_size: 4
    draft_bot_account: vbotbuildovich
    merge_bot_account: vbotbuildovich
    update_bot_account: vbotbuildovich

merge_queue:
  max_parallel_checks: 2
